### ISSUE TITLE
[Connecting to kafka] :: Too long time (about 4 minutes) is needed to establish connection

### ISSUE THREAD

**Issue by alena-bobryk** [alshpak/kafka_data_viewer#1]
Too long time (about 4 minutes) is needed to establish connection. During this time the program hangs and does not response. The command line contains records:
![kafka connecting](https://user-images.githubusercontent.com/47312823/52193055-3dc70200-285e-11e9-81e5-f977252ae15a.jpg)

When connection is established - "Next records attempt" records are constantly appearing in command line.

**Comment by alshpak** [comment]
fixed in 0.1
