### ISSUE TITLE
["Read topic" tab] :: Records of topic are not displayed after some other topic was already open

### ISSUE THREAD

**Issue by alena-bobryk** [alshpak/kafka_data_viewer#5]
**Steps to reproduce:**

1. Go to "Read topic" tab.
2. Open any topic and wait until records are displayed.
3. Open some other topic.

**Expected result:** Records of new topic are displayed in the table.
**Actual result:** Records of previous topic are displayed in the table.

**Comment by alshpak** [comment]
fixed in 0.1
