### ISSUE TITLE
[Connections list] :: Use "connection name" instead of "kafka host" in "Connections list" and tabs names

### ISSUE THREAD

**Issue by alena-bobryk** [alshpak/kafka_data_viewer#6]
[Connections list] :: Use "connection name" instead of "kafka host" in "Connections list" and tabs names

See details in scrennshorts:
![11](https://user-images.githubusercontent.com/47312823/52547409-93f4f180-2dd8-11e9-95e3-fee66d973f12.png)

![connection name2](https://user-images.githubusercontent.com/47312823/52474197-d46e2880-2ba8-11e9-9fd1-30132ef23367.png)

**Comment by alshpak** [comment]
Fixed in 0.1.1
