### ISSUE TITLE
[Logging tab] :: Records don't increment during some time from connection establishing

### ISSUE THREAD

**Issue by alena-bobryk** [alshpak/kafka_data_viewer#7]
Tool displays some records for selected topics and then stops to do it. The old version of this tool (not upgraded) works well in parallel with this version.
 
See details in screnshort:
![loging tab1](https://user-images.githubusercontent.com/47312823/52474675-367b5d80-2baa-11e9-9e41-ac20f95c52f0.png)

**Comment by alena-bobryk** [comment]
The errors from console are sent to the developer by skype

**Comment by alshpak** [comment]
Fixed in 0.1.1
