### ISSUE TITLE
["Read Topic" tab] :: ["Click to read next portion of data" button] :: No new data returns after clicking this button

### ISSUE THREAD

**Issue by alena-bobryk** [alshpak/kafka_data_viewer#8]
*Steps to reproduce:*
1. Open ""Read Topic" tab".
2. Apply "All" value in "Items to read per partition" dropdown.
3. Select any topic to read and wait until rows are displayed.
4. Press "Click to read next portion of data" button.

*Expected result:* Next portion of data is displayed.
*Actual result:* Next portion of data is NOT displayed. Previous result is still displayed.

**Comment by alena-bobryk** [comment]
![next portion of data](https://user-images.githubusercontent.com/47312823/52475389-64fa3800-2bac-11e9-8d2f-e35a79e2bb4e.png)

**Comment by alshpak** [comment]
Fixed in 0.1.1
